### ISSUE TITLE
waiter.Await(wb => wb.Document.Body.OuterHtml) sometimes doesn't return

### ISSUE THREAD

**Issue by Rexfelis** [LeastOne/WebBrowserWaiter#2]
I can process hundreds of documents, but it seems after around 650ish documents are processed, waiter doesn't return with the document body and my service hangs:

(edited for clarity)

My code looks more like this:

``` C#
 public string GetHtmlFromUrl(string url)
 {
      string html = string.Empty;

      using (var waiter = new WebBrowserWaiter.WebBrowserWaiter())
      {
           string html = string.Empty;

           InternetSetCookie(url, null, cookie + expired);
           waiter.Await(wb => wb.Navigate(url));
           try
           {
                html = waiter.Await(wb => wb.Document.Body.OuterHtml);
           }
           catch(Exception ex)
           {
           }
      }

      return html;
 }
```

Occasionally, a null reference exception will be thrown when I try to access the WebBrowser document.  If the html string comes back null or empty I've been retrying, but maybe that is aggravating the issue?  Is there a better way to handle this if the document is null?

**Comment by Rexfelis** [comment]
I should expand on the above:

My code looks more like this:

public string GetHtmlFromUrl(string url)
{
using (var waiter = new WebBrowserWaiter.WebBrowserWaiter())
{
     InternetSetCookie(url, null, cookie + expired);
     waiter.Await(wb => wb.Navigate(url));
     try
     {
          html = waiter.Await(wb => wb.Document.Body.OuterHtml);
     }
     catch(Exception ex)
     {
     }
}
}

Occasionally, a null reference exception will be thrown when I try to access the WebBrowser document.  If the html string comes back null or empty I've been retrying, but maybe that is aggravating the issue?  Is there a better way to handle this if the document is null?

**Comment by LeastOne** [comment]
Hmm, first a couple of questions come to mind ... Are you making requests to multiple hosts or a single host? Can this invalid state be reproduced consistently?

Second, in an effort to try and diagnose the problem further you could try enabling display of the browser to see if there is a script error of some sort that is occurring you can do this by passing a value of `true` to the `visibility` constructor argument.

``` C#
new WebBrowserWaiter(true)
```

Additionally, maybe try slowing the request rate to see if that has any impact. The default wait is zero, you can change it by assigning the `DefaultWait` property:

``` C#
waiter.DefaultWait = TimeSpan.FromSeconds(1);
```

Or providing it as the first argument to an `Await` call:

``` C#
// These two invocations are equivalent
waiter.Await(500, wb => wb.Navigate(url));
waiter.Await(TimeSpan.FromSeconds(0.5), wb=> wb.Navigate(url));
```

Lastly, a parting thought. The WebBrowser control is quirky, the WebBrowserWaiter alleviates some of that quirkiness but not all. Its important to keep in mind that the WebBrowser's real advantage is that it can process pages requiring JavaScript. If you don't need this capability you may want to use the standard [WebClient](https://msdn.microsoft.com/en-us/library/system.net.webclient) or something like [SimpleBrowser](https://github.com/axefrog/SimpleBrowser). Also, in many instances I've needed WebBrowser just to complete a login process, but once the login process is completed I can use the cookies I've collected with a [WebClient](https://msdn.microsoft.com/en-us/library/system.net.webclient) to more efficiently retrieve what I need. That may not be applicable in your case but I think it's worth mentioning.

**Comment by Rexfelis** [comment]
I'm making requests to a single host.  I can't reproduce it consistently, although it seems to happen around a certain number of navigations.

I will make the window visible and see if that sheds some light.  I'll also try to slow the request wait.

I'm mostly using a HttpClient.  However, in this case I need to make a javascript call and get the document elements afterwards.  I was not able to do that with a HttpClient nor HttpWebRequest.  Which is unfortunate because my service is run on Azure and Azure won't allow WebBrowsers to run.  I'm having to run the service locally and then sync my databases.  Quite the pain.

**Comment by LeastOne** [comment]
Gotcha, sounds like you've got the right approach.

One thing about the wait, I've been looking at it here for the last 15 minutes and I think I may have identified a bug which could also relate to your situation. Here's my theory.

When `wb.Navigate(url)` is called its run on a thread managed by `WebBrowser` separate from the thread in which the `waiter` was instantiated. When this occurs the `waiter` is listening for a `Navigating` event to be fired by the `WebBrowser`. Once it fires it sets a flag that tells subsequent `waiter.Await` calls to wait until the `WebBrowser`'s `DocumentCompleted` event fires.

In most cases this seems to function correctly, however I believe that in some instances it's possible for the `wb.Navigate(url)` call to execute and for the the next `waiter.Await` call to begin before the `WebBrowser`'s `Navigating` event fires. In this scenario the subsequent `waiter.Await` doesn't wait for the `DocumentCompleted` event because the flag isn't set, essentially it assumes the document has finished loading when in fact it has not.

For your situation, you could test this by adding a `Thread.Sleep` between the `waiter.Await` calls. Note that it would have to be outside the `Await` not within one of the provided lambda's. Something like this:

``` C#
using (var waiter = new WebBrowserWaiter()) {
    waiter.Await(wb => wb.Navigate("url"));
    Thread.Sleep(50); // Experiment with different values maybe within the range of 50-1000
    var html = waiter.Await(wb => wb.Document.Body.OuterHtml);
}
```

As far as this goes for `WebBrowserWaiter` I need to do some more testing to verify this. It looks like when this scenario occurs any wait that is specified is all but ignored, that can be fixed rather easily, but it won't address the root issue. In order to address the root issue I think the waiter will need to have two different types of methods `Await`'s and `Navigate`'s. The later would be a new method type for any lambda that resulted in the `WebBrowser` issuing a new request, essentially it wouldn't return until the `Navigating` event had been fired. This is going to need some though though as this could make use of `WebBrowserWaiter` quite confusing.

**Comment by Rexfelis** [comment]
Using Thread.Sleep(250) between waiters seems to prevent nearly all exceptions on getting the WebBrowser.Document.  However, I'm still running into hangs eventually.  Will try to make the window visible and see if I can figure out why it is hanging.

**Comment by LeastOne** [comment]
Evolving my previous suggestion, perhaps a better method would be along the lines of ...

``` C#
using (var waiter = new WebBrowserWaiter()) {
    waiter.Await(wb => wb.Navigate("url"));

    HtmlDocument document = null;

    // Wait for up to a minute (50ms * 1200 = 1 minute)
    for (var i = 0; i < 1200 && document == null; i++)
    {
        Thread.Sleep(50);
        document = waiter.Await(p => p.Document);
    }

    var html = document.Body.OuterHtml;
}
```

**Comment by Rexfelis** [comment]
The hang is due to a JavaScript error.  I googled ways to get around this and I tried to do something like this:

``` C#
System.Windows.Forms.HtmlDocument document = waiter.Await(wb => wb.Document);
document.Window.Error += OnWebBrowserDocumentWindowError;

private void OnWebBrowserDocumentWindowError(object sender, HtmlElementErrorEventArgs e)
{
    e.Handled = true;
}
```

However, when adding the event, it throws an exception with "Specified cast is not valid"

**Comment by LeastOne** [comment]
What cast is it referring to? Does it work if you do something like this ...

``` C#
using (var waiter = new WebBrowserWaiter())
{
    string html = null;

    waiter.Await(
        p => p.Navigate(uri + "error"),
        p => p.Document.Window.Error += (q, r) => r.Handled = true,
        p => html = p.Document.Body.OuterHtml
    );
}
```

**Comment by Rexfelis** [comment]
Using that code it does continue on script errors, but eventually it would hang on the await.  I made the browser visible and it was popping up "out of memory" errors.

**Comment by LeastOne** [comment]
What version of Internet Explorer is installed on the instance? I just executed a unit test that downloads a 1000 different pages with 1 MiB in random content successfully and the process memory never exceeded 150 MiB. I have Internet Explorer 11 installed.

**Comment by LeastOne** [comment]
I just had a similar issue where a hang was caused by a JavaScript error. Setting `ScriptErrorsSuppressed` to `true` in the first `Await` ended up solving the problem. The incident reminded me of this thread. Not sure if it will be useful to you months later, but for what its worth as well as for others I'd thought I'd post an update. Here's an example of what that call looks like:

``` C#
using (var waiter = new WebBrowserWaiter())
{
    waiter.Await(
        p => {
            p.ScriptErrorsSuppressed = true;
            p.Navigate("url"),
        }
    );
}
```
